export const denominacoes = [
  "Outra",
  "Adventista",
  "Assembleia de Deus",
  "Batista",
  "Bola de Neve",
  "Casa da Bênção",
  "Comunidade Cristã",
  "Congregação Cristã no Brasil",
  "Deus é Amor",
  "Evangelho Quadrangular",
  "Igreja Episcopal",
  "Igreja Internacional da Graça de Deus",
  "Igreja Luterana",
  "Igreja Metodista",
  "Igreja Pentecostal",
  "Igreja Presbiteriana",
  "Igreja Renascer em Cristo",
  "Igreja Sara Nossa Terra",
  "Igreja Universal do Reino de Deus",
  "Ministério Apascentar",
  "Ministério Fonte da Vida",
  "Ministério Internacional da Restauração",
  "Ministério Voz da Verdade",
  "Nova Vida",
  "O Brasil para Cristo",
  "Paz e Vida",
  "Projeto Vida",
  "Verbo da Vida",
  "Videira",
  "Vitória em Cristo",
  "Wesleyana",
  "Zion Church"
];