SET ROLE neondb_owner;



-- DROP de roles existentes
DROP ROLE IF EXISTS role_anonimo;
DROP ROLE IF EXISTS role_usuario;
DROP ROLE IF EXISTS role_levita;
DROP ROLE IF EXISTS role_ministro;
DROP ROLE IF EXISTS role_lider;
DROP ROLE IF EXISTS role_administrador;
DROP ROLE IF EXISTS role_api;
DROP ROLE IF EXISTS role_sistema;



-- criação de ROLEs sem login
CREATE ROLE role_anonimo WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE role_usuario WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE role_levita WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE role_ministro WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE role_lider WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE role_administrador WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';



-- criação de ROLE de acesso
CREATE ROLE role_api WITH
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  INHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 10
  PASSWORD 'senha-temporaria'
  VALID UNTIL 'infinity';

GRANT role_anonimo       TO role_api;
GRANT role_usuario       TO role_api;
GRANT role_levita        TO role_api;
GRANT role_ministro      TO role_api;
GRANT role_lider         TO role_api;
GRANT role_administrador TO role_api;



-- criação de ROLE de sistema (triggers, functions etc.)
CREATE ROLE role_sistema WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';