SET ROLE neondb_owner;



-- DROP de roles existentes
DROP ROLE IF EXISTS r_anonimo;
DROP ROLE IF EXISTS r_usuario;
DROP ROLE IF EXISTS r_levita;
DROP ROLE IF EXISTS r_ministro;
DROP ROLE IF EXISTS r_lider;
DROP ROLE IF EXISTS r_administrador;
DROP ROLE IF EXISTS r_api;
DROP ROLE IF EXISTS r_sistema;



-- criação de ROLEs sem login
CREATE ROLE r_anonimo WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE r_usuario WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE r_levita WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE r_ministro WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE r_lider WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';

CREATE ROLE r_administrador WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';



-- criação de ROLE com login
CREATE ROLE r_api WITH
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 10
  PASSWORD 'senha-temporaria'
  VALID UNTIL 'infinity';



-- criação de ROLE de sistema, que lida com routines SECURITY DEFINER
CREATE ROLE r_sistema WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT 0
  PASSWORD NULL
  VALID UNTIL 'infinity';